### ISSUE TITLE
application_only_auth

### ISSUE THREAD

**Issue by cburke496** [wesny/CCVB#1]
When I try running our code, I get this error:

Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from py import Twitter
  File "/home/students/2014/christopher.burke/CCVB/py/Twitter.py", line 2, in <module>
    from application_only_auth import Client
ImportError: No module named application_only_auth

Anybody know what this is?

**Comment by wesny** [comment]
Is this fixed?

**Comment by cburke496** [comment]
no

**Comment by cburke496** [comment]
Ok, I tried moving the application_only_auth folder into the py folder and it works now. I don't know why it was working for Jack before.
